"""Official WTO data layer for Trade Cases Flask app."""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

DATA_PATH = Path(os.environ.get("WTO_OFFICIAL_DATA", "data/wto_disputes_official.json"))
AUTO_IMPORT = os.environ.get("WTO_AUTO_IMPORT", "0") == "1"


def load_official_disputes(fallback: List[Dict[str, Any]] | None = None) -> List[Dict[str, Any]]:
    """Load official WTO JSON generated by scripts/wto_official_importer.py.
    If missing and WTO_AUTO_IMPORT=1, it imports all cases before returning.
    """
    fallback = fallback or []
    if not DATA_PATH.exists() and AUTO_IMPORT:
        try:
            subprocess.check_call([
                sys.executable, "scripts/wto_official_importer.py", "--all", "--out", str(DATA_PATH)
            ])
        except Exception as exc:
            print(f"[warn] WTO auto import failed: {exc}")
    if not DATA_PATH.exists():
        return fallback
    try:
        payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))
        cases = payload.get("cases", payload if isinstance(payload, list) else [])
        if isinstance(cases, list) and cases:
            return cases
    except Exception as exc:
        print(f"[warn] could not read official WTO data: {exc}")
    return fallback


def normalize_country(value: Any) -> str:
    s = str(value or "").strip().lower()
    aliases = {
        "usa": "united states", "us": "united states", "u.s.": "united states",
        "united states of america": "united states",
        "eu": "european union", "ec": "european union", "european communities": "european union",
        "turkey": "türkiye", "republic of türkiye": "türkiye",
        "ksa": "saudi arabia", "kingdom of saudi arabia": "saudi arabia",
        "republic of korea": "korea", "korea, republic of": "korea",
    }
    return aliases.get(s, s)


def split_csv(value: Any) -> List[str]:
    return [normalize_country(x) for x in str(value or "").split(",") if normalize_country(x)]


def party_haystack(d: Dict[str, Any], keys: List[str]) -> str:
    parts: List[str] = []
    for key in keys:
        value = d.get(key, "")
        if isinstance(value, list):
            parts.extend(str(x) for x in value)
        else:
            parts.append(str(value))
    return " ".join(normalize_country(x) for x in parts)


def official_metadata() -> Dict[str, Any]:
    if DATA_PATH.exists():
        try:
            payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))
            return payload.get("metadata", {}) if isinstance(payload, dict) else {}
        except Exception:
            return {}
    return {}
